// Mocks generated by Mockito 5.4.6 from annotations
// in lexi_core/test/features/dictionary/domain/use_cases/lookup_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lexi_core/features/dictionary/domain/entities/language.dart'
    as _i5;
import 'package:lexi_core/features/dictionary/domain/entities/lookup_result.dart'
    as _i4;
import 'package:lexi_core/features/dictionary/domain/repositories/dictionary_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DictionaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDictionaryRepository extends _i1.Mock
    implements _i2.DictionaryRepository {
  MockDictionaryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LookupResult> lookup({
    required String? query,
    required _i5.Language? targetLanguage,
    required bool? aiEnabled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookup,
          [],
          {
            #query: query,
            #targetLanguage: targetLanguage,
            #aiEnabled: aiEnabled,
          },
        ),
        returnValue:
            _i3.Future<_i4.LookupResult>.value(_i6.dummyValue<_i4.LookupResult>(
          this,
          Invocation.method(
            #lookup,
            [],
            {
              #query: query,
              #targetLanguage: targetLanguage,
              #aiEnabled: aiEnabled,
            },
          ),
        )),
      ) as _i3.Future<_i4.LookupResult>);
}
