// Mocks generated by Mockito 5.4.6 from annotations
// in lexi_core/test/features/vocabulary/domain/use_cases/vocab_use_cases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lexi_core/features/dictionary/domain/entities/input_type.dart'
    as _i5;
import 'package:lexi_core/features/dictionary/domain/entities/language.dart'
    as _i6;
import 'package:lexi_core/features/vocabulary/domain/entities/topic.dart'
    as _i7;
import 'package:lexi_core/features/vocabulary/domain/entities/vocab_record.dart'
    as _i4;
import 'package:lexi_core/features/vocabulary/domain/repositories/vocab_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [VocabRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVocabRepository extends _i1.Mock implements _i2.VocabRepository {
  MockVocabRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> save(_i4.VocabRecord? record) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [record],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.VocabRecord>> getAll({
    String? topicId,
    _i5.InputType? inputType,
    _i6.Language? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #topicId: topicId,
            #inputType: inputType,
            #language: language,
          },
        ),
        returnValue:
            _i3.Future<List<_i4.VocabRecord>>.value(<_i4.VocabRecord>[]),
      ) as _i3.Future<List<_i4.VocabRecord>>);

  @override
  _i3.Future<_i4.VocabRecord?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i3.Future<_i4.VocabRecord?>.value(),
      ) as _i3.Future<_i4.VocabRecord?>);

  @override
  _i3.Future<void> update(_i4.VocabRecord? record) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [record],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> existsByHeadword(
    String? headword,
    _i6.Language? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #existsByHeadword,
          [
            headword,
            language,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i4.VocabRecord?> getByHeadword(
    String? headword,
    _i6.Language? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByHeadword,
          [
            headword,
            language,
          ],
        ),
        returnValue: _i3.Future<_i4.VocabRecord?>.value(),
      ) as _i3.Future<_i4.VocabRecord?>);

  @override
  _i3.Future<List<_i7.Topic>> getTopics() => (super.noSuchMethod(
        Invocation.method(
          #getTopics,
          [],
        ),
        returnValue: _i3.Future<List<_i7.Topic>>.value(<_i7.Topic>[]),
      ) as _i3.Future<List<_i7.Topic>>);

  @override
  _i3.Future<void> addTopic(_i7.Topic? topic) => (super.noSuchMethod(
        Invocation.method(
          #addTopic,
          [topic],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTopic(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTopic,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
