// Mocks generated by Mockito 5.4.6 from annotations
// in lexi_core/test/features/dictionary/data/repositories/dictionary_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lexi_core/features/dictionary/data/sources/free_dictionary_source.dart'
    as _i8;
import 'package:lexi_core/features/dictionary/data/sources/gemini_dictionary_source.dart'
    as _i2;
import 'package:lexi_core/features/dictionary/domain/entities/input_type.dart'
    as _i5;
import 'package:lexi_core/features/dictionary/domain/entities/language.dart'
    as _i6;
import 'package:lexi_core/features/dictionary/domain/entities/lookup_result.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GeminiDictionarySource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiDictionarySource extends _i1.Mock
    implements _i2.GeminiDictionarySource {
  MockGeminiDictionarySource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LookupResult> lookup({
    required String? query,
    required _i5.InputType? inputType,
    required _i6.Language? targetLanguage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookup,
          [],
          {
            #query: query,
            #inputType: inputType,
            #targetLanguage: targetLanguage,
          },
        ),
        returnValue:
            _i3.Future<_i4.LookupResult>.value(_i7.dummyValue<_i4.LookupResult>(
          this,
          Invocation.method(
            #lookup,
            [],
            {
              #query: query,
              #inputType: inputType,
              #targetLanguage: targetLanguage,
            },
          ),
        )),
      ) as _i3.Future<_i4.LookupResult>);

  @override
  _i3.Future<String> discoverWord({required _i6.Language? targetLanguage}) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverWord,
          [],
          {#targetLanguage: targetLanguage},
        ),
        returnValue: _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #discoverWord,
            [],
            {#targetLanguage: targetLanguage},
          ),
        )),
      ) as _i3.Future<String>);
}

/// A class which mocks [FreeDictionarySource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFreeDictionarySource extends _i1.Mock
    implements _i8.FreeDictionarySource {
  MockFreeDictionarySource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.WordPhraseResult> lookup(String? word) => (super.noSuchMethod(
        Invocation.method(
          #lookup,
          [word],
        ),
        returnValue: _i3.Future<_i4.WordPhraseResult>.value(
            _i7.dummyValue<_i4.WordPhraseResult>(
          this,
          Invocation.method(
            #lookup,
            [word],
          ),
        )),
      ) as _i3.Future<_i4.WordPhraseResult>);
}
