// Mocks generated by Mockito 5.4.6 from annotations
// in lexi_core/test/features/dictionary/presentation/providers/lookup_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lexi_core/features/dictionary/domain/entities/input_type.dart'
    as _i9;
import 'package:lexi_core/features/dictionary/domain/entities/language.dart'
    as _i5;
import 'package:lexi_core/features/dictionary/domain/entities/lookup_result.dart'
    as _i4;
import 'package:lexi_core/features/dictionary/domain/use_cases/lookup_use_case.dart'
    as _i2;
import 'package:lexi_core/features/vocabulary/domain/entities/cefr_level.dart'
    as _i10;
import 'package:lexi_core/features/vocabulary/domain/entities/topic.dart'
    as _i11;
import 'package:lexi_core/features/vocabulary/domain/entities/vocab_record.dart'
    as _i8;
import 'package:lexi_core/features/vocabulary/domain/repositories/vocab_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LookupUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLookupUseCase extends _i1.Mock implements _i2.LookupUseCase {
  MockLookupUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LookupResult> execute({
    required String? query,
    required _i5.Language? targetLanguage,
    required bool? aiAvailable,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #query: query,
            #targetLanguage: targetLanguage,
            #aiAvailable: aiAvailable,
          },
        ),
        returnValue:
            _i3.Future<_i4.LookupResult>.value(_i6.dummyValue<_i4.LookupResult>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #query: query,
              #targetLanguage: targetLanguage,
              #aiAvailable: aiAvailable,
            },
          ),
        )),
      ) as _i3.Future<_i4.LookupResult>);
}

/// A class which mocks [VocabRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVocabRepository extends _i1.Mock implements _i7.VocabRepository {
  MockVocabRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> save(_i8.VocabRecord? record) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [record],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.VocabRecord>> getAll({
    required _i5.Language? language,
    String? topicId,
    _i9.InputType? inputType,
    _i10.CEFRLevel? maxCefrLevel,
    bool? dueOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #language: language,
            #topicId: topicId,
            #inputType: inputType,
            #maxCefrLevel: maxCefrLevel,
            #dueOnly: dueOnly,
          },
        ),
        returnValue:
            _i3.Future<List<_i8.VocabRecord>>.value(<_i8.VocabRecord>[]),
      ) as _i3.Future<List<_i8.VocabRecord>>);

  @override
  _i3.Future<_i8.VocabRecord?> getById(
    String? id, {
    required _i5.Language? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
          {#language: language},
        ),
        returnValue: _i3.Future<_i8.VocabRecord?>.value(),
      ) as _i3.Future<_i8.VocabRecord?>);

  @override
  _i3.Future<void> update(_i8.VocabRecord? record) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [record],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> delete(
    String? id, {
    required _i5.Language? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
          {#language: language},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> existsByHeadword(
    String? headword,
    _i5.Language? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #existsByHeadword,
          [
            headword,
            language,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i8.VocabRecord?> getByHeadword(
    String? headword,
    _i5.Language? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByHeadword,
          [
            headword,
            language,
          ],
        ),
        returnValue: _i3.Future<_i8.VocabRecord?>.value(),
      ) as _i3.Future<_i8.VocabRecord?>);

  @override
  _i3.Future<List<_i11.Topic>> getTopics() => (super.noSuchMethod(
        Invocation.method(
          #getTopics,
          [],
        ),
        returnValue: _i3.Future<List<_i11.Topic>>.value(<_i11.Topic>[]),
      ) as _i3.Future<List<_i11.Topic>>);

  @override
  _i3.Future<void> addTopic(_i11.Topic? topic) => (super.noSuchMethod(
        Invocation.method(
          #addTopic,
          [topic],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTopic(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTopic,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
